stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - data/raw/spam.csv
    outs:
    - data/processed/ingested.csv

  process:
    cmd: python src/data_processing.py
    deps:
    - src/data_processing.py
    - data/processed/ingested.csv
    outs:
    - data/processed/clean.csv

  features:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/processed/clean.csv
    outs:
    - data/processed/features.pkl
    - models/vectorizer.pkl

  split:
    cmd: python src/train_test_split.py
    deps:
    - src/train_test_split.py
    - data/processed/features.pkl
    outs:
    - data/processed/train.pkl
    - data/processed/test.pkl

  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed/train.pkl
    outs:
    - models/model.pkl

  evaluate:
    cmd: python src/evaluation.py
    deps:
    - src/evaluation.py
    - models/model.pkl
    - data/processed/test.pkl
    metrics:
    - dvclive/metrics.json

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
